name: "Push Build"
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  linux-build-jvm:
    name: Linux - Benchmarks - Java
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 17 ]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Reclaim Disk Space
        run: .github/ci-prerequisites.sh
      - name: Install JDK {{ matrix.java }}
        uses: joschi/setup-jdk@e87a7cec853d2dd7066adf837fe12bf0f3d45e52
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          check-latest: true
      - name: Run Benchmarks
        run: |
          mvn -s .github/mvn-settings.xml clean install
      - name: Persist Benchmark Results
        run: |
          git config --global user.name 'Sgitario'
          git config --global user.email 'josecarvajalhilario@gmail.com'
          git add --all
          git commit -m "Update benchmark results"
      - name: Push Benchmark Results
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true